FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
# -u per non bufferizzare i log e vederli subito
CMD ["python", "-u", "main.py"]