services:
  simulator: 
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    networks:
      - mars_net

  # 1.BROKER (RabbitMQ)
  broker:
    image: rabbitmq:3-management-alpine
    user: "999:999"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mars_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      retries: 20
      interval: 5s
      timeout: 5s
    hostname: broker
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # 2.DATABASE (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rules_db
      MYSQL_USER: mars_user
      MYSQL_PASSWORD: mars_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mars_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 5s
      timeout: 3s
      retries: 30

  # 3.INGESTOR 
  ingestion_service:
    build: 
      context: ./ingestion_service
    environment:
      # host.docker.internal se il simulatore gira fuori dal compose
      #- SIMULATOR_URL=http://host.docker.internal:8080 
      - SIMULATOR_URL=http://simulator:8080
      - BROKER_URL=amqp://guest:guest@broker:5672/
    depends_on:
      broker:
        condition: service_healthy
      simulator:
        condition: service_started
    networks:
      - mars_net
    restart: unless-stopped

  # 4.RULE ENGINE 
  rule_engine:
    build: 
      context: ./rule_engine
    environment:
      - BROKER_URL=amqp://guest:guest@broker:5672/
      - DB_HOST=db
      - DB_USER=mars_user
      - DB_PASSWORD=mars_password
      - DB_NAME=rules_db
      # La stringa di connessione punta al servizio "db" sulla porta 3306
      - DB_URL=mysql+pymysql://mars_user:mars_password@db:3306/rules_db
      # host.docker.internal se il simulatore gira fuori dal compose
      #- SIMULATOR_URL=http://host.docker.internal:8080 
      - SIMULATOR_URL=http://simulator:8080
    depends_on:
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
      simulator:
        condition: service_started
    networks:
      - mars_net
    restart: unless-stopped

  # 5. BACKEND
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=db
      - DB_USER=mars_user
      - DB_PASSWORD=mars_password
      - DB_NAME=rules_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - mars_net
    restart: unless-stopped

  # 6. FRONTEND
  frontend:
    build:
      context: ./frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:80"
    networks:
      - mars_net
    restart: unless-stopped

networks:
  mars_net:
    driver: bridge

volumes:
  rabbitmq_data: #Appoggia i dati di rabbitmq
  db_data: # Salva i dati di MySQL in modo persistente